export const OBTENER_POSTS = 'OBTENER_POSTS';
export const OBTENER_POSTS_EXITO = 'OBTENER_POSTS_EXITO';
export const OBTENER_POSTS_ERROR = 'OBTENER_POST_ERROR';

export const ELIMINAR_POST = 'ELIMINAR_POST';

export const INICIAR_SESION = 'INICIAR_SESION';
export const CERRAR_SESION = 'CERRAR_SESION';
